name: Check manifest compliance
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-policy-checks:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: alexellis/setup-arkade@v2
        with:
          conftest: 0.47.0
      - name: Verify conftest cli tool is available
        run: |
          conftest -v
      - name: Check compliance to policies
        run: |
          conftest test -p ./tests/conftest_policies/ ./k8s_manifests/
